-- MySQL Script generated by MySQL Workbench
-- Tue May 19 22:15:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema concentrados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema concentrados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concentrados` DEFAULT CHARACTER SET utf8 ;
USE `concentrados` ;

-- -----------------------------------------------------
-- Table `concentrados`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentrados`.`rol` (
  `id_Rol` INT NOT NULL AUTO_INCREMENT,
  `nombreRol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concentrados`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentrados`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `NombreCliente` VARCHAR(45) NULL,
  `apellidosCliente` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `edad` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NOT NULL,
  `id_Rol` INT NOT NULL,
  `pass` VARCHAR(1000) NULL,
  PRIMARY KEY (`idCliente`),
  CONSTRAINT `fk_Cliente_rol1`
    FOREIGN KEY (`id_Rol`)
    REFERENCES `concentrados`.`rol` (`id_Rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concentrados`.`estadoPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentrados`.`estadoPedido` (
  `idEstadoPedido` INT NOT NULL AUTO_INCREMENT,
  `nombreEstado` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstadoPedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concentrados`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentrados`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `fechaPedido` VARCHAR(45) NULL,
  `idCliente` INT NOT NULL,
  `idEstadoPedido` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  CONSTRAINT `fk_Pedidos_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `concentrados`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_estadoPedido1`
    FOREIGN KEY (`idEstadoPedido`)
    REFERENCES `concentrados`.`estadoPedido` (`idEstadoPedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concentrados`.`puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentrados`.`puesto` (
  `idPuesto` INT NOT NULL AUTO_INCREMENT,
  `nombrePuesto` VARCHAR(45) NULL,
  PRIMARY KEY (`idPuesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concentrados`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentrados`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `nombreEmp` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `id_Rol` INT NOT NULL,
  `pass` VARCHAR(1000) NULL,
  `idPuesto` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`),
CONSTRAINT `fk_Empleado_rol1`
    FOREIGN KEY (`id_Rol`)
    REFERENCES `concentrados`.`rol` (`id_Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_puesto1`
    FOREIGN KEY (`idPuesto`)
    REFERENCES `concentrados`.`puesto` (`idPuesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concentrados`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentrados`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `nombreProveedor` VARCHAR(45) NULL,
  `contacto` VARCHAR(45) NULL,
  `NIT` VARCHAR(45) NULL,
  `correoP` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concentrados`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentrados`.`Factura` (
  `idFacturaMP` INT NOT NULL AUTO_INCREMENT,
  `numeroFac` VARCHAR(45) NULL,
  `Monto` INT NULL,
  `Fecha` DOUBLE NULL,
  `idProveedor` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idFacturaMP`),
 CONSTRAINT `fk_materiaPrima_Proveedor1`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `concentrados`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Empleado1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `concentrados`.`Empleado` (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concentrados`.`Produccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentrados`.`Produccion` (
  `idProduccion` INT NOT NULL AUTO_INCREMENT,
  `fechaP` VARCHAR(45) NULL,
  `estadoP` VARCHAR(45) NULL,
  `idPedido` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idProduccion`),
  CONSTRAINT `fk_Produccion_Pedido1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `concentrados`.`Pedido` (`idPedido`)
,
  CONSTRAINT `fk_Produccion_Empleado1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `concentrados`.`Empleado` (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concentrados`.`Receta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentrados`.`Receta` (
  `idReceta` INT NOT NULL AUTO_INCREMENT,
  `nombreReceta` VARCHAR(45) NULL,
  PRIMARY KEY (`idReceta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concentrados`.`materiaPrima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentrados`.`materiaPrima` (
  `idMateriaPrima` INT NOT NULL AUTO_INCREMENT,
  `NombreMP` VARCHAR(45) NULL,
  PRIMARY KEY (`idMateriaPrima`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concentrados`.`detalleCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentrados`.`detalleCompra` (
  `idDetalleCompra` INT NOT NULL AUTO_INCREMENT,
  `idMateriaPrima` INT NOT NULL,
  `cantidadMP` VARCHAR(45) NULL,
  `precioMP` DOUBLE NULL,
  `idCompraMP` INT NOT NULL,
  PRIMARY KEY (`idDetalleCompra`),
  CONSTRAINT `fk_detalleCompra_comprasPrima1`
    FOREIGN KEY (`idCompraMP`)
    REFERENCES `concentrados`.`Factura` (`idFacturaMP`),
    CONSTRAINT `fk_detalleCompra_materiaPrima1`
    FOREIGN KEY (`idMateriaPrima`)
    REFERENCES `concentrados`.`materiaPrima` (`idMateriaPrima`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concentrados`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentrados`.`Inventario` (
  `idInventario` INT NOT NULL AUTO_INCREMENT,
  `idMateriaPrima` INT NOT NULL,
  `Existencias` INT NULL,
  `idDetalleCompra` INT NOT NULL,
  PRIMARY KEY (`idInventario`),
 CONSTRAINT `fk_Inventario_detalleCompra1`
    FOREIGN KEY (`idDetalleCompra`)
    REFERENCES `concentrados`.`detalleCompra` (`idDetalleCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_materiaPrima1`
    FOREIGN KEY (`idMateriaPrima`)
    REFERENCES `concentrados`.`materiaPrima` (`idMateriaPrima`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concentrados`.`detalleReceta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentrados`.`detalleReceta` (
  `idDetalleReceta` INT NOT NULL AUTO_INCREMENT,
  `idMateriaPrima` INT NOT NULL,
  `cantidaSa` INT NULL,
  `fechaSa` VARCHAR(45) NULL,
  `idInventario` INT NOT NULL,
  `iidReceta` INT NOT NULL,
  PRIMARY KEY (`idDetalleReceta`),
 CONSTRAINT `fk_Kardex_Inventario1`
    FOREIGN KEY (`idInventario`)
    REFERENCES `concentrados`.`Inventario` (`idInventario`),
  CONSTRAINT `fk_Kardex_materiaPrima1`
    FOREIGN KEY (`idMateriaPrima`)
    REFERENCES `concentrados`.`materiaPrima` (`idMateriaPrima`),
  CONSTRAINT `fk_detalleReceta_Receta1`
    FOREIGN KEY (`iidReceta`)
    REFERENCES `concentrados`.`Receta` (`idReceta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concentrados`.`detallePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentrados`.`detallePedido` (
  `idDetallePedido` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `idReceta` INT NOT NULL,
  `IdPedido` INT NOT NULL,
  PRIMARY KEY (`idDetallePedido`),
 CONSTRAINT `fk_detallePedido_Receta1`
    FOREIGN KEY (`idReceta`)
    REFERENCES `concentrados`.`Receta` (`idReceta`),
  CONSTRAINT `fk_detallePedido_Pedido1`
    FOREIGN KEY (`IdPedido`)
    REFERENCES `concentrados`.`Pedido` (`idPedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concentrados`.`Salidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentrados`.`Salidas` (
  `idSalida` INT NOT NULL AUTO_INCREMENT,
  `idProduccion` INT NOT NULL,
  `NombreCliente` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  `montoTotal` DOUBLE NULL,
  `estadoSalida` VARCHAR(45) NULL,
  PRIMARY KEY (`idSalida`),
CONSTRAINT `fk_ventaF_Produccion1`
    FOREIGN KEY (`idProduccion`)
    REFERENCES `concentrados`.`Produccion` (`idProduccion`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
