-- ==========================================================
-- DICCIONARIO DE DATOS COMPLETO - CONCENTRADOS EL GORDITO
-- Documentación Técnica Exhaustiva (SQL COMMENT)
-- Total Tablas: 31 | Total Columnas Documentadas: 219
-- ==========================================================

ALTER TABLE `auditoria` COMMENT = 'Registro de auditoría y bitácora de eventos del sistema';
ALTER TABLE `auditoria` MODIFY COLUMN `idAuditoria` int(11) NOT NULL auto_increment COMMENT 'Campo idAuditoria en tabla auditoria';
ALTER TABLE `auditoria` MODIFY COLUMN `idUsuario` int(11) NULL DEFAULT NULL COMMENT 'ID del usuario que ejecutó la acción auditada (FK usuarios)';
ALTER TABLE `auditoria` MODIFY COLUMN `username` varchar(100) NULL DEFAULT NULL COMMENT 'Nombre de usuario o correo de quien realizó la acción';
ALTER TABLE `auditoria` MODIFY COLUMN `tipo_evento` enum('login','logout','vista','modulo','crud','error','sistema') NOT NULL DEFAULT 'sistema' COMMENT 'Campo tipo_evento en tabla auditoria';
ALTER TABLE `auditoria` MODIFY COLUMN `modulo` varchar(100) NULL DEFAULT NULL COMMENT 'Módulo o sección del sistema donde se originó el evento';
ALTER TABLE `auditoria` MODIFY COLUMN `descripcion` text NULL DEFAULT NULL COMMENT 'Detalle descriptivo del evento o cambio realizado';
ALTER TABLE `auditoria` MODIFY COLUMN `ip_address` varchar(45) NULL DEFAULT NULL COMMENT 'Campo ip_address en tabla auditoria';
ALTER TABLE `auditoria` MODIFY COLUMN `user_agent` varchar(255) NULL DEFAULT NULL COMMENT 'Campo user_agent en tabla auditoria';
ALTER TABLE `auditoria` MODIFY COLUMN `fecha_hora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo fecha_hora en tabla auditoria';
ALTER TABLE `cliente` COMMENT = 'Catálogo de clientes registrados en el sistema';
ALTER TABLE `cliente` MODIFY COLUMN `idCliente` int(11) NOT NULL auto_increment COMMENT 'Identificador único y autoincremental del cliente';
ALTER TABLE `cliente` MODIFY COLUMN `NombreCliente` varchar(45) NULL DEFAULT NULL COMMENT 'Nombres del cliente o razón social';
ALTER TABLE `cliente` MODIFY COLUMN `apellidosCliente` varchar(45) NULL DEFAULT NULL COMMENT 'Apellidos del cliente o nombre comercial';
ALTER TABLE `cliente` MODIFY COLUMN `telefono` varchar(45) NULL DEFAULT NULL COMMENT 'Número de teléfono de contacto del cliente';
ALTER TABLE `cliente` MODIFY COLUMN `edad` varchar(45) NULL DEFAULT NULL COMMENT 'Campo edad en tabla cliente';
ALTER TABLE `cliente` MODIFY COLUMN `genero` varchar(45) NULL DEFAULT NULL COMMENT 'Campo genero en tabla cliente';
ALTER TABLE `cliente` MODIFY COLUMN `idUsuario` int(11) NOT NULL COMMENT 'ID de usuario vinculado al cliente para acceso al portal (FK usuarios)';
ALTER TABLE `cliente` MODIFY COLUMN `idEmpresa` int(11) NOT NULL DEFAULT '1' COMMENT 'ID de la empresa a cuya cartera pertenece el cliente (FK empresas)';
ALTER TABLE `detallecompra` COMMENT = 'Detalle de compras de materia prima realizadas a proveedores';
ALTER TABLE `detallecompra` MODIFY COLUMN `idDetalleCompra` int(11) NOT NULL auto_increment COMMENT 'Identificador único del ítem en el detalle de compra';
ALTER TABLE `detallecompra` MODIFY COLUMN `idMateriaPrima` int(11) NOT NULL COMMENT 'ID de la materia prima adquirida (FK materiaprima)';
ALTER TABLE `detallecompra` MODIFY COLUMN `cantidadMP` int(45) NULL DEFAULT NULL COMMENT 'Campo cantidadMP en tabla detallecompra';
ALTER TABLE `detallecompra` MODIFY COLUMN `precioMP` double NULL DEFAULT NULL COMMENT 'Campo precioMP en tabla detallecompra';
ALTER TABLE `detallecompra` MODIFY COLUMN `idFacturaMP` int(11) NOT NULL COMMENT 'Campo idFacturaMP en tabla detallecompra';
ALTER TABLE `detallepedido` COMMENT = 'Detalle de productos incluidos en cada pedido de cliente';
ALTER TABLE `detallepedido` MODIFY COLUMN `idDetallePedido` int(11) NOT NULL auto_increment COMMENT 'Identificador único de la línea de detalle del pedido';
ALTER TABLE `detallepedido` MODIFY COLUMN `cantidad` int(11) NULL DEFAULT NULL COMMENT 'Cantidad de sacos o unidades solicitadas';
ALTER TABLE `detallepedido` MODIFY COLUMN `idReceta` int(11) NOT NULL COMMENT 'Campo idReceta en tabla detallepedido';
ALTER TABLE `detallepedido` MODIFY COLUMN `IdPedido` int(11) NOT NULL COMMENT 'Campo IdPedido en tabla detallepedido';
ALTER TABLE `detallereceta` COMMENT = 'Composición de materias primas por cada fórmula o receta de concentrado';
ALTER TABLE `detallereceta` MODIFY COLUMN `idDetalleReceta` int(11) NOT NULL auto_increment COMMENT 'Identificador único del ingrediente dentro de la receta';
ALTER TABLE `detallereceta` MODIFY COLUMN `idMateriaPrima` int(11) NOT NULL COMMENT 'ID de la materia prima utilizada en la mezcla (FK materiaprima)';
ALTER TABLE `detallereceta` MODIFY COLUMN `cantidaSa` int(11) NULL DEFAULT NULL COMMENT 'Campo cantidaSa en tabla detallereceta';
ALTER TABLE `detallereceta` MODIFY COLUMN `fechaSa` varchar(45) NULL DEFAULT NULL COMMENT 'Campo fechaSa en tabla detallereceta';
ALTER TABLE `detallereceta` MODIFY COLUMN `idInventario` int(11) NOT NULL COMMENT 'Campo idInventario en tabla detallereceta';
ALTER TABLE `detallereceta` MODIFY COLUMN `IdReceta` int(11) NOT NULL COMMENT 'Campo IdReceta en tabla detallereceta';
ALTER TABLE `empleado` COMMENT = 'Registro de personal y colaboradores de la empresa';
ALTER TABLE `empleado` MODIFY COLUMN `idEmpleado` int(11) NOT NULL auto_increment COMMENT 'Identificador único y autoincremental del empleado';
ALTER TABLE `empleado` MODIFY COLUMN `nombreEmp` varchar(45) NULL DEFAULT NULL COMMENT 'Nombres del colaborador';
ALTER TABLE `empleado` MODIFY COLUMN `apellido` varchar(45) NULL DEFAULT NULL COMMENT 'Apellidos del colaborador';
ALTER TABLE `empleado` MODIFY COLUMN `genero` varchar(45) NULL DEFAULT NULL COMMENT 'Campo genero en tabla empleado';
ALTER TABLE `empleado` MODIFY COLUMN `idPuesto` int(11) NOT NULL COMMENT 'ID del puesto o cargo laboral asignado (FK puesto)';
ALTER TABLE `empleado` MODIFY COLUMN `idUsuario` int(11) NOT NULL COMMENT 'ID de cuenta de usuario asociada al empleado (FK usuarios)';
ALTER TABLE `empleado` MODIFY COLUMN `activo` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Campo activo en tabla empleado';
ALTER TABLE `empleado` MODIFY COLUMN `idEmpresa` int(11) NOT NULL DEFAULT '1' COMMENT 'ID de la empresa en la que labora el empleado (FK empresas)';
ALTER TABLE `empresas` COMMENT = 'Registro de empresas y comercios afiliados para arquitectura SaaS Multi-Tenant';
ALTER TABLE `empresas` MODIFY COLUMN `idEmpresa` int(11) NOT NULL auto_increment COMMENT 'Identificador único y autoincremental de la empresa o comercio';
ALTER TABLE `empresas` MODIFY COLUMN `idUsuarioDueno` int(11) NOT NULL DEFAULT '0' COMMENT 'ID del usuario dueño o administrador principal de la empresa (FK usuarios)';
ALTER TABLE `empresas` MODIFY COLUMN `nombreEmpresa` varchar(150) NOT NULL COMMENT 'Razón social o nombre comercial visible del negocio';
ALTER TABLE `empresas` MODIFY COLUMN `slug` varchar(100) NOT NULL COMMENT 'Identificador alfanumérico único para subdominios o URL (ej: santaelena)';
ALTER TABLE `empresas` MODIFY COLUMN `direccion` varchar(255) NULL DEFAULT NULL COMMENT 'Dirección física de la sede, planta o sucursal principal';
ALTER TABLE `empresas` MODIFY COLUMN `telefono` varchar(50) NULL DEFAULT NULL COMMENT 'Número telefónico fijo o PBX de atención al cliente';
ALTER TABLE `empresas` MODIFY COLUMN `correo` varchar(150) NULL DEFAULT NULL COMMENT 'Correo electrónico oficial para notificaciones y pedidos';
ALTER TABLE `empresas` MODIFY COLUMN `whatsapp` varchar(50) NULL DEFAULT NULL COMMENT 'Número de WhatsApp directo con código de país para atención rápida';
ALTER TABLE `empresas` MODIFY COLUMN `logo` varchar(255) NULL DEFAULT NULL COMMENT 'Ruta relativa de la imagen o logotipo del comercio';
ALTER TABLE `empresas` MODIFY COLUMN `wompiAppId` varchar(255) NULL DEFAULT NULL COMMENT 'ID de aplicación (Client ID / App ID) de la pasarela Wompi SV del comercio';
ALTER TABLE `empresas` MODIFY COLUMN `wompiApiKey` varchar(255) NULL DEFAULT NULL COMMENT 'Clave secreta (API Secret Key) de Wompi SV para autenticar cobros directos';
ALTER TABLE `empresas` MODIFY COLUMN `wompiActivo` tinyint(1) NULL DEFAULT '0' COMMENT 'Estado de la pasarela Wompi del negocio: 1 = Habilitada, 0 = Deshabilitada';
ALTER TABLE `empresas` MODIFY COLUMN `activo` tinyint(1) NULL DEFAULT '1' COMMENT 'Estado operativo del comercio en la plataforma: 1 = Activo, 0 = Suspendido';
ALTER TABLE `empresas` MODIFY COLUMN `fechaRegistro` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha y hora exacta en la que se registró la empresa en el sistema';
ALTER TABLE `empresa_info` COMMENT = 'Información institucional, misión, visión y contacto de la empresa';
ALTER TABLE `empresa_info` MODIFY COLUMN `idEmpresa` int(11) NOT NULL auto_increment COMMENT 'Campo idEmpresa en tabla empresa_info';
ALTER TABLE `empresa_info` MODIFY COLUMN `nombre` varchar(150) NOT NULL DEFAULT 'Concentrados El Gordito' COMMENT 'Nombre comercial oficial de la empresa';
ALTER TABLE `empresa_info` MODIFY COLUMN `eslogan` varchar(255) NULL DEFAULT 'Nutrición Animal de Alto Rendimiento' COMMENT 'Lema o eslogan corporativo';
ALTER TABLE `empresa_info` MODIFY COLUMN `resumen` text NULL DEFAULT NULL COMMENT 'Resumen descriptivo de la trayectoria y propuesta de valor';
ALTER TABLE `empresa_info` MODIFY COLUMN `mision` text NULL DEFAULT NULL COMMENT 'Declaración de misión corporativa';
ALTER TABLE `empresa_info` MODIFY COLUMN `vision` text NULL DEFAULT NULL COMMENT 'Declaración de visión corporativa a futuro';
ALTER TABLE `empresa_info` MODIFY COLUMN `telefono` varchar(50) NULL DEFAULT '+503 2440-1234' COMMENT 'Número de teléfono fijo o PBX principal';
ALTER TABLE `empresa_info` MODIFY COLUMN `telefono_movil` varchar(50) NULL DEFAULT '+503 7890-5678' COMMENT 'Número de teléfono móvil de contacto adicional';
ALTER TABLE `empresa_info` MODIFY COLUMN `whatsapp` varchar(50) NULL DEFAULT '+50378905678' COMMENT 'Número de WhatsApp oficial con código de país';
ALTER TABLE `empresa_info` MODIFY COLUMN `correo` varchar(100) NULL DEFAULT 'ventas@concentradoselgordito.com' COMMENT 'Correo electrónico oficial de atención al cliente';
ALTER TABLE `empresa_info` MODIFY COLUMN `direccion` varchar(255) NULL DEFAULT 'Carretera Panamericana Km 65, El Salvador' COMMENT 'Dirección física de la planta principal y salas de venta';
ALTER TABLE `empresa_info` MODIFY COLUMN `horario` varchar(255) NULL DEFAULT 'Lunes a Viernes: 7:00 AM – 5:00 PM | Sábados: 7:00 AM – 12:00 MD' COMMENT 'Texto con los días y horarios de atención al público';
ALTER TABLE `empresa_info` MODIFY COLUMN `logo` varchar(255) NULL DEFAULT 'views/Recursos/logo.png' COMMENT 'Campo logo en tabla empresa_info';
ALTER TABLE `empresa_info` MODIFY COLUMN `facebook` varchar(255) NULL DEFAULT 'https://facebook.com' COMMENT 'URL de la página de Facebook oficial';
ALTER TABLE `empresa_info` MODIFY COLUMN `instagram` varchar(255) NULL DEFAULT 'https://instagram.com' COMMENT 'URL del perfil de Instagram oficial';
ALTER TABLE `empresa_info` MODIFY COLUMN `actualizado_en` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP on update current_timestamp() COMMENT 'Campo actualizado_en en tabla empresa_info';
ALTER TABLE `estadopedido` COMMENT = 'Catálogo de estados de ciclo de vida de los pedidos';
ALTER TABLE `estadopedido` MODIFY COLUMN `idEstadoPedido` int(11) NOT NULL COMMENT 'Identificador único del estado de pedido';
ALTER TABLE `estadopedido` MODIFY COLUMN `nombreEstado` varchar(45) NULL DEFAULT NULL COMMENT 'Nombre descriptivo del estado (ej: Pendiente, Pagado, Despachado, Cancelado)';
ALTER TABLE `factura` COMMENT = 'Registro de facturación y comprobantes fiscales de venta';
ALTER TABLE `factura` MODIFY COLUMN `idFacturaMP` int(11) NOT NULL COMMENT 'Campo idFacturaMP en tabla factura';
ALTER TABLE `factura` MODIFY COLUMN `numeroFac` varchar(45) NULL DEFAULT NULL COMMENT 'Campo numeroFac en tabla factura';
ALTER TABLE `factura` MODIFY COLUMN `Monto` int(11) NULL DEFAULT NULL COMMENT 'Campo Monto en tabla factura';
ALTER TABLE `factura` MODIFY COLUMN `Fecha` varchar(50) NULL DEFAULT NULL COMMENT 'Campo Fecha en tabla factura';
ALTER TABLE `factura` MODIFY COLUMN `idProveedor` int(11) NOT NULL COMMENT 'Campo idProveedor en tabla factura';
ALTER TABLE `factura` MODIFY COLUMN `idEmpleado` int(11) NOT NULL COMMENT 'Campo idEmpleado en tabla factura';
ALTER TABLE `factura` MODIFY COLUMN `idEmpresa` int(11) NOT NULL DEFAULT '1' COMMENT 'ID de la empresa emisora del documento fiscal (FK empresas)';
ALTER TABLE `historico_precios_promociones` COMMENT = 'Historial de variaciones de precios y promociones aplicadas a productos';
ALTER TABLE `historico_precios_promociones` MODIFY COLUMN `idHistorico` int(11) NOT NULL auto_increment COMMENT 'Identificador único del registro histórico';
ALTER TABLE `historico_precios_promociones` MODIFY COLUMN `idReceta` int(11) NOT NULL COMMENT 'Campo idReceta en tabla historico_precios_promociones';
ALTER TABLE `historico_precios_promociones` MODIFY COLUMN `tipo_cambio` enum('nivelacion','promocion') NOT NULL DEFAULT 'nivelacion' COMMENT 'Campo tipo_cambio en tabla historico_precios_promociones';
ALTER TABLE `historico_precios_promociones` MODIFY COLUMN `precio_anterior` decimal(10,2) NOT NULL COMMENT 'Campo precio_anterior en tabla historico_precios_promociones';
ALTER TABLE `historico_precios_promociones` MODIFY COLUMN `precio_nuevo` decimal(10,2) NOT NULL COMMENT 'Campo precio_nuevo en tabla historico_precios_promociones';
ALTER TABLE `historico_precios_promociones` MODIFY COLUMN `porcentaje_descuento` int(11) NULL DEFAULT '0' COMMENT 'Campo porcentaje_descuento en tabla historico_precios_promociones';
ALTER TABLE `historico_precios_promociones` MODIFY COLUMN `fecha_inicio` datetime NULL DEFAULT NULL COMMENT 'Campo fecha_inicio en tabla historico_precios_promociones';
ALTER TABLE `historico_precios_promociones` MODIFY COLUMN `fecha_fin` datetime NULL DEFAULT NULL COMMENT 'Campo fecha_fin en tabla historico_precios_promociones';
ALTER TABLE `historico_precios_promociones` MODIFY COLUMN `motivo` varchar(255) NULL DEFAULT NULL COMMENT 'Razón o justificación del cambio de precio o campaña';
ALTER TABLE `historico_precios_promociones` MODIFY COLUMN `usuario` varchar(100) NOT NULL DEFAULT 'admin' COMMENT 'Campo usuario en tabla historico_precios_promociones';
ALTER TABLE `historico_precios_promociones` MODIFY COLUMN `estado` enum('activa','finalizada','cancelada','aplicada') NOT NULL DEFAULT 'aplicada' COMMENT 'Campo estado en tabla historico_precios_promociones';
ALTER TABLE `historico_precios_promociones` MODIFY COLUMN `creado_en` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo creado_en en tabla historico_precios_promociones';
ALTER TABLE `inventario` COMMENT = 'Catálogo de productos terminados, alimentos balanceados y stock disponible';
ALTER TABLE `inventario` MODIFY COLUMN `idInventario` int(11) NOT NULL COMMENT 'Identificador único y autoincremental del producto terminado';
ALTER TABLE `inventario` MODIFY COLUMN `idMateriaPrima` int(11) NOT NULL COMMENT 'Campo idMateriaPrima en tabla inventario';
ALTER TABLE `inventario` MODIFY COLUMN `Existencias` double NULL DEFAULT NULL COMMENT 'Campo Existencias en tabla inventario';
ALTER TABLE `inventario` MODIFY COLUMN `idEmpresa` int(11) NOT NULL DEFAULT '1' COMMENT 'ID de la empresa dueña del producto en inventario (FK empresas)';
ALTER TABLE `materiaprima` COMMENT = 'Catálogo de materias primas e insumos para la molienda y elaboración de mezclas';
ALTER TABLE `materiaprima` MODIFY COLUMN `idMateriaPrima` int(11) NOT NULL COMMENT 'Identificador único de la materia prima o insumo';
ALTER TABLE `materiaprima` MODIFY COLUMN `NombreMP` varchar(45) NULL DEFAULT NULL COMMENT 'Campo NombreMP en tabla materiaprima';
ALTER TABLE `materiaprima` MODIFY COLUMN `idEmpresa` int(11) NOT NULL DEFAULT '1' COMMENT 'ID de la empresa propietaria de la materia prima (FK empresas)';
ALTER TABLE `modulos` COMMENT = 'Catálogo de módulos del sistema para control de acceso y navegación';
ALTER TABLE `modulos` MODIFY COLUMN `idModulo` int(11) NOT NULL auto_increment COMMENT 'Identificador único del módulo del sistema';
ALTER TABLE `modulos` MODIFY COLUMN `nombre` varchar(100) NOT NULL COMMENT 'Nombre visible del módulo en el menú lateral';
ALTER TABLE `modulos` MODIFY COLUMN `controlador` varchar(100) NOT NULL COMMENT 'Archivo controlador PHP asociado al módulo';
ALTER TABLE `modulos` MODIFY COLUMN `icono` varchar(50) NOT NULL DEFAULT 'fa-folder' COMMENT 'Clase de icono FontAwesome para representación gráfica';
ALTER TABLE `modulos` MODIFY COLUMN `orden` int(11) NOT NULL DEFAULT '0' COMMENT 'Número de orden jerárquico para visualización en el menú';
ALTER TABLE `modulos` MODIFY COLUMN `activo` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Estado del módulo: 1 = Activo, 0 = Desactivado';
ALTER TABLE `pagos` COMMENT = 'Registro de transacciones de pago procesadas vía Wompi SV y otros métodos';
ALTER TABLE `pagos` MODIFY COLUMN `idPago` int(11) NOT NULL auto_increment COMMENT 'Identificador único y autoincremental de la transacción de pago';
ALTER TABLE `pagos` MODIFY COLUMN `idUsuario` int(11) NOT NULL COMMENT 'ID del usuario o comprador que realizó el pago (FK usuarios)';
ALTER TABLE `pagos` MODIFY COLUMN `idPlanPago` int(11) NULL DEFAULT NULL COMMENT 'ID del plan de membresía contratado si aplica (FK plan_pago)';
ALTER TABLE `pagos` MODIFY COLUMN `monto` decimal(10,2) NOT NULL COMMENT 'Monto liquidado de la transacción en dólares (USD)';
ALTER TABLE `pagos` MODIFY COLUMN `moneda` varchar(3) NOT NULL DEFAULT 'USD' COMMENT 'Campo moneda en tabla pagos';
ALTER TABLE `pagos` MODIFY COLUMN `metodo_pago` varchar(50) NOT NULL DEFAULT 'stripe' COMMENT 'Campo metodo_pago en tabla pagos';
ALTER TABLE `pagos` MODIFY COLUMN `estado` enum('pendiente','completado','fallido','reembolsado','cancelado') NOT NULL DEFAULT 'pendiente' COMMENT 'Estado del pago: pendiente, completado, fallido o cancelado';
ALTER TABLE `pagos` MODIFY COLUMN `referencia` varchar(255) NULL DEFAULT NULL COMMENT 'Código de referencia único de la transacción (ej: CONC-12345)';
ALTER TABLE `pagos` MODIFY COLUMN `descripcion` text NULL DEFAULT NULL COMMENT 'Descripción del concepto de cobro y datos de autorización';
ALTER TABLE `pagos` MODIFY COLUMN `fecha_hora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo fecha_hora en tabla pagos';
ALTER TABLE `pagos` MODIFY COLUMN `ip_address` varchar(45) NULL DEFAULT NULL COMMENT 'Campo ip_address en tabla pagos';
ALTER TABLE `pagos` MODIFY COLUMN `user_agent` varchar(255) NULL DEFAULT NULL COMMENT 'Campo user_agent en tabla pagos';
ALTER TABLE `pagos` MODIFY COLUMN `metadata` longtext NULL DEFAULT NULL COMMENT 'Estructura JSON con los metadatos completos y respuesta de la pasarela Wompi';
ALTER TABLE `pagos` MODIFY COLUMN `idEmpresa` int(11) NOT NULL DEFAULT '1' COMMENT 'ID de la empresa que recibe los fondos de la transacción (FK empresas)';
ALTER TABLE `pedido` COMMENT = 'Registro de órdenes de pedido de productos generadas por clientes o ventas';
ALTER TABLE `pedido` MODIFY COLUMN `idPedido` int(11) NOT NULL auto_increment COMMENT 'Identificador único y autoincremental del pedido';
ALTER TABLE `pedido` MODIFY COLUMN `fechaPedido` varchar(45) NULL DEFAULT NULL COMMENT 'Fecha y hora en que fue emitida la orden de compra';
ALTER TABLE `pedido` MODIFY COLUMN `idCliente` int(11) NOT NULL COMMENT 'ID del cliente comprador (FK cliente)';
ALTER TABLE `pedido` MODIFY COLUMN `idEstadoPedido` int(11) NOT NULL COMMENT 'Estado actual de la orden (FK estadopedido)';
ALTER TABLE `pedido` MODIFY COLUMN `idEmpresa` int(11) NOT NULL DEFAULT '1' COMMENT 'ID de la empresa que vende y despacha la orden (FK empresas)';
ALTER TABLE `permisos_rol` COMMENT = 'Matriz de asignación de permisos de módulos principales por rol';
ALTER TABLE `permisos_rol` MODIFY COLUMN `idPermiso` int(11) NOT NULL auto_increment COMMENT 'Identificador único de la asignación de permiso';
ALTER TABLE `permisos_rol` MODIFY COLUMN `id_Rol` int(11) NOT NULL COMMENT 'ID del rol receptor del permiso (FK rol)';
ALTER TABLE `permisos_rol` MODIFY COLUMN `idModulo` int(11) NOT NULL COMMENT 'ID del módulo autorizado (FK modulos)';
ALTER TABLE `permisos_rol` MODIFY COLUMN `permitido` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Indicador de acceso: 1 = Permitido, 0 = Denegado';
ALTER TABLE `permisos_submodulo` COMMENT = 'Matriz de asignación de permisos a submódulos por rol';
ALTER TABLE `permisos_submodulo` MODIFY COLUMN `idPermisoSub` int(11) NOT NULL auto_increment COMMENT 'Campo idPermisoSub en tabla permisos_submodulo';
ALTER TABLE `permisos_submodulo` MODIFY COLUMN `id_Rol` int(11) NOT NULL COMMENT 'ID del rol receptor (FK rol)';
ALTER TABLE `permisos_submodulo` MODIFY COLUMN `idSubmodulo` int(11) NOT NULL COMMENT 'ID del submódulo autorizado (FK submodulos)';
ALTER TABLE `permisos_submodulo` MODIFY COLUMN `permitido` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Indicador de acceso: 1 = Permitido, 0 = Denegado';
ALTER TABLE `permisos_usuario_submodulo` COMMENT = 'Asignaciones personalizadas de submódulos específicas para empleados o usuarios';
ALTER TABLE `permisos_usuario_submodulo` MODIFY COLUMN `idPermisoUserSub` int(11) NOT NULL auto_increment COMMENT 'Campo idPermisoUserSub en tabla permisos_usuario_submodulo';
ALTER TABLE `permisos_usuario_submodulo` MODIFY COLUMN `idUsuario` int(11) NOT NULL COMMENT 'ID del usuario al que se le concede o restringe el submódulo (FK usuarios)';
ALTER TABLE `permisos_usuario_submodulo` MODIFY COLUMN `idSubmodulo` int(11) NOT NULL COMMENT 'ID del submódulo configurado (FK submodulos)';
ALTER TABLE `permisos_usuario_submodulo` MODIFY COLUMN `permitido` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Indicador de acceso individual: 1 = Permitido, 0 = Revocado';
ALTER TABLE `plan_pago` COMMENT = 'Catálogo de planes de suscripción y membresías para acceso a la plataforma';
ALTER TABLE `plan_pago` MODIFY COLUMN `idPlanPago` int(11) NOT NULL auto_increment COMMENT 'Identificador único del plan de membresía';
ALTER TABLE `plan_pago` MODIFY COLUMN `nombrePlan` varchar(100) NOT NULL COMMENT 'Nombre del plan (ej: Básico, Profesional, Agro Industrial)';
ALTER TABLE `plan_pago` MODIFY COLUMN `descripcion` text NULL DEFAULT NULL COMMENT 'Detalle de beneficios, límites y módulos habilitados';
ALTER TABLE `plan_pago` MODIFY COLUMN `monto` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Costo periódico de la membresía en USD';
ALTER TABLE `plan_pago` MODIFY COLUMN `duracion_dias` int(11) NOT NULL DEFAULT '30' COMMENT 'Duración del ciclo de suscripción en días (ej: 30, 365)';
ALTER TABLE `plan_pago` MODIFY COLUMN `activo` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Estado de comercialización del plan: 1 = Activo, 0 = Inactivo';
ALTER TABLE `plan_pago` MODIFY COLUMN `creado_en` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo creado_en en tabla plan_pago';
ALTER TABLE `plan_pago` MODIFY COLUMN `actualizado_en` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP on update current_timestamp() COMMENT 'Campo actualizado_en en tabla plan_pago';
ALTER TABLE `produccion` COMMENT = 'Registro de órdenes y lotes de producción y molienda de concentrados';
ALTER TABLE `produccion` MODIFY COLUMN `idProduccion` int(11) NOT NULL COMMENT 'Identificador único de la orden de producción';
ALTER TABLE `produccion` MODIFY COLUMN `fechaP` varchar(45) NULL DEFAULT NULL COMMENT 'Campo fechaP en tabla produccion';
ALTER TABLE `produccion` MODIFY COLUMN `estadoP` varchar(45) NULL DEFAULT NULL COMMENT 'Campo estadoP en tabla produccion';
ALTER TABLE `produccion` MODIFY COLUMN `idPedido` int(11) NOT NULL COMMENT 'Campo idPedido en tabla produccion';
ALTER TABLE `produccion` MODIFY COLUMN `idEmpleado` int(11) NOT NULL COMMENT 'ID del operador o encargado de planta responsable (FK empleado)';
ALTER TABLE `produccion` MODIFY COLUMN `idEmpresa` int(11) NOT NULL DEFAULT '1' COMMENT 'ID de la empresa que ejecuta la orden de producción (FK empresas)';
ALTER TABLE `proveedor` COMMENT = 'Catálogo de proveedores de insumos, materias primas y servicios';
ALTER TABLE `proveedor` MODIFY COLUMN `idProveedor` int(11) NOT NULL COMMENT 'Identificador único del proveedor';
ALTER TABLE `proveedor` MODIFY COLUMN `nombreProveedor` varchar(45) NULL DEFAULT NULL COMMENT 'Razón social o nombre comercial del proveedor';
ALTER TABLE `proveedor` MODIFY COLUMN `contacto` varchar(45) NULL DEFAULT NULL COMMENT 'Nombre del representante o ejecutivo de ventas del proveedor';
ALTER TABLE `proveedor` MODIFY COLUMN `NIT` varchar(45) NULL DEFAULT NULL COMMENT 'Campo NIT en tabla proveedor';
ALTER TABLE `proveedor` MODIFY COLUMN `correoP` varchar(45) NULL DEFAULT NULL COMMENT 'Campo correoP en tabla proveedor';
ALTER TABLE `proveedor` MODIFY COLUMN `telefono` varchar(45) NULL DEFAULT NULL COMMENT 'Teléfono de contacto de la empresa proveedora';
ALTER TABLE `proveedor` MODIFY COLUMN `idEmpresa` int(11) NOT NULL DEFAULT '1' COMMENT 'ID de la empresa asociada a este proveedor (FK empresas)';
ALTER TABLE `puesto` COMMENT = 'Catálogo de cargos y puestos laborales de la estructura organizacional';
ALTER TABLE `puesto` MODIFY COLUMN `idPuesto` int(11) NOT NULL COMMENT 'Identificador único del puesto de trabajo';
ALTER TABLE `puesto` MODIFY COLUMN `nombrePuesto` varchar(45) NULL DEFAULT NULL COMMENT 'Título del cargo (ej: Administrador, Gerente de Planta, Vendedor, Molinero)';
ALTER TABLE `receta` COMMENT = 'Catálogo de fórmulas maestras y recetas nutricionales para la elaboración de concentrados';
ALTER TABLE `receta` MODIFY COLUMN `idReceta` int(11) NOT NULL COMMENT 'Identificador único de la fórmula o receta';
ALTER TABLE `receta` MODIFY COLUMN `nombreReceta` varchar(45) NULL DEFAULT NULL COMMENT 'Nombre de la fórmula (ej: Concentrado Postura Premium, Engorde Cerdos)';
ALTER TABLE `receta` MODIFY COLUMN `PrecioUnitario` double NOT NULL COMMENT 'Campo PrecioUnitario en tabla receta';
ALTER TABLE `receta` MODIFY COLUMN `precio_anterior` double NULL DEFAULT NULL COMMENT 'Precio anterior antes de promoción o descuento';
ALTER TABLE `receta` MODIFY COLUMN `en_promocion` tinyint(1) NULL DEFAULT '0' COMMENT 'Campo en_promocion en tabla receta';
ALTER TABLE `receta` MODIFY COLUMN `porcentaje_descuento` int(11) NULL DEFAULT '0' COMMENT 'Campo porcentaje_descuento en tabla receta';
ALTER TABLE `receta` MODIFY COLUMN `fecha_inicio_promo` datetime NULL DEFAULT NULL COMMENT 'Fecha y hora de inicio de promoción para esta receta';
ALTER TABLE `receta` MODIFY COLUMN `fecha_fin_promo` datetime NULL DEFAULT NULL COMMENT 'Fecha y hora de fin de promoción para esta receta';
ALTER TABLE `receta` MODIFY COLUMN `precio_base_regular` decimal(10,2) NULL DEFAULT NULL COMMENT 'Precio base regular establecido para el lote';
ALTER TABLE `recuperacion_pass` COMMENT = 'Registro y control de tokens temporales para restablecimiento seguro de contraseña';
ALTER TABLE `recuperacion_pass` MODIFY COLUMN `id` int(11) NOT NULL auto_increment COMMENT 'Identificador único del token de recuperación';
ALTER TABLE `recuperacion_pass` MODIFY COLUMN `email` varchar(100) NOT NULL COMMENT 'Correo electrónico del usuario solicitante';
ALTER TABLE `recuperacion_pass` MODIFY COLUMN `token` varchar(64) NOT NULL COMMENT 'Token criptográfico unívoco de un solo uso';
ALTER TABLE `recuperacion_pass` MODIFY COLUMN `expiracion` datetime NOT NULL COMMENT 'Fecha y hora límite de validez del enlace (vigencia de 1 hora)';
ALTER TABLE `recuperacion_pass` MODIFY COLUMN `usado` tinyint(1) NULL DEFAULT '0' COMMENT 'Indicador de consumo del token: 1 = Consumido, 0 = Vigente';
ALTER TABLE `recuperacion_pass` MODIFY COLUMN `creado_en` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo creado_en en tabla recuperacion_pass';
ALTER TABLE `rol` COMMENT = 'Catálogo de roles y perfiles de seguridad jerárquicos del sistema';
ALTER TABLE `rol` MODIFY COLUMN `id_Rol` int(11) NOT NULL COMMENT 'Identificador único del rol de usuario';
ALTER TABLE `rol` MODIFY COLUMN `nombreRol` varchar(45) NULL DEFAULT NULL COMMENT 'Nombre del rol (ej: Administrador, Empleado, Cliente, Gerente General)';
ALTER TABLE `rol` MODIFY COLUMN `descripcion` varchar(255) NULL DEFAULT NULL COMMENT 'Descripción funcional de las responsabilidades y nivel de acceso';
ALTER TABLE `rol` MODIFY COLUMN `idRolPadre` int(11) NULL DEFAULT NULL COMMENT 'ID del rol superior para herencia recursiva de permisos (FK rol)';
ALTER TABLE `rol` MODIFY COLUMN `submodulos` longtext NULL DEFAULT NULL COMMENT 'Arreglo JSON con los IDs de submódulos permitidos explícitamente';
ALTER TABLE `rol` MODIFY COLUMN `acceso_total` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Bandera de superusuario con acceso irrestricto: 1 = Sí, 0 = No';
ALTER TABLE `rol` MODIFY COLUMN `activo` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Estado del rol: 1 = Activo, 0 = Desactivado';
ALTER TABLE `salidas` COMMENT = 'Registro de salidas, bajas y mermas de inventario y materia prima';
ALTER TABLE `salidas` MODIFY COLUMN `idSalida` int(11) NOT NULL COMMENT 'Identificador único del movimiento de salida';
ALTER TABLE `salidas` MODIFY COLUMN `idProduccion` int(11) NOT NULL COMMENT 'Campo idProduccion en tabla salidas';
ALTER TABLE `salidas` MODIFY COLUMN `NombreCliente` varchar(45) NULL DEFAULT NULL COMMENT 'Campo NombreCliente en tabla salidas';
ALTER TABLE `salidas` MODIFY COLUMN `fecha` varchar(45) NULL DEFAULT NULL COMMENT 'Fecha y hora del movimiento de salida';
ALTER TABLE `salidas` MODIFY COLUMN `montoTotal` double NULL DEFAULT NULL COMMENT 'Monto total valorizado de la salida en USD';
ALTER TABLE `salidas` MODIFY COLUMN `estadoSalida` varchar(45) NULL DEFAULT NULL COMMENT 'Campo estadoSalida en tabla salidas';
ALTER TABLE `sesiones_activas` COMMENT = 'Monitoreo de sesiones de usuario activas en tiempo real para seguridad y auditoría';
ALTER TABLE `sesiones_activas` MODIFY COLUMN `session_id` varchar(128) NOT NULL COMMENT 'ID de sesión nativo de PHP (PHPSESSID)';
ALTER TABLE `sesiones_activas` MODIFY COLUMN `idUsuario` int(11) NULL DEFAULT NULL COMMENT 'ID del usuario autenticado (FK usuarios)';
ALTER TABLE `sesiones_activas` MODIFY COLUMN `username` varchar(100) NULL DEFAULT NULL COMMENT 'Nombre de usuario en sesión activa';
ALTER TABLE `sesiones_activas` MODIFY COLUMN `id_Rol` int(11) NULL DEFAULT NULL COMMENT 'ID del rol con el que navega el usuario (FK rol)';
ALTER TABLE `sesiones_activas` MODIFY COLUMN `nombre_usuario` varchar(200) NULL DEFAULT NULL COMMENT 'Campo nombre_usuario en tabla sesiones_activas';
ALTER TABLE `sesiones_activas` MODIFY COLUMN `login_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo login_time en tabla sesiones_activas';
ALTER TABLE `sesiones_activas` MODIFY COLUMN `last_activity` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP on update current_timestamp() COMMENT 'Campo last_activity en tabla sesiones_activas';
ALTER TABLE `sesiones_activas` MODIFY COLUMN `ip_address` varchar(45) NULL DEFAULT NULL COMMENT 'Campo ip_address en tabla sesiones_activas';
ALTER TABLE `sesiones_activas` MODIFY COLUMN `user_agent` varchar(255) NULL DEFAULT NULL COMMENT 'Navegador web y sistema operativo del usuario';
ALTER TABLE `sesiones_activas` MODIFY COLUMN `activo` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Campo activo en tabla sesiones_activas';
ALTER TABLE `submodulos` COMMENT = 'Catálogo de submódulos y pantallas funcionales detalladas del sistema';
ALTER TABLE `submodulos` MODIFY COLUMN `idSubmodulo` int(11) NOT NULL auto_increment COMMENT 'Identificador único del submódulo';
ALTER TABLE `submodulos` MODIFY COLUMN `idModulo` int(11) NOT NULL COMMENT 'ID del módulo principal al que pertenece (FK modulos)';
ALTER TABLE `submodulos` MODIFY COLUMN `nombre` varchar(100) NOT NULL COMMENT 'Nombre visible de la función o pantalla';
ALTER TABLE `submodulos` MODIFY COLUMN `controlador_accion` varchar(100) NOT NULL COMMENT 'Ruta y parámetros del controlador (ej: controllerCliente.php?accion=nuevo)';
ALTER TABLE `submodulos` MODIFY COLUMN `icono` varchar(50) NOT NULL DEFAULT 'fa-circle-notch' COMMENT 'Icono FontAwesome asociado al submódulo';
ALTER TABLE `submodulos` MODIFY COLUMN `orden` int(11) NOT NULL DEFAULT '0' COMMENT 'Posición en el menú desplegable';
ALTER TABLE `submodulos` MODIFY COLUMN `activo` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Estado de disponibilidad: 1 = Habilitado, 0 = Deshabilitado';
ALTER TABLE `usuarios` COMMENT = 'Cuentas de acceso, credenciales y autenticación de usuarios del sistema';
ALTER TABLE `usuarios` MODIFY COLUMN `idUsuario` int(11) NOT NULL auto_increment COMMENT 'Identificador único y autoincremental de la cuenta de usuario';
ALTER TABLE `usuarios` MODIFY COLUMN `username` varchar(45) NOT NULL COMMENT 'Nombre de usuario único o correo electrónico para iniciar sesión';
ALTER TABLE `usuarios` MODIFY COLUMN `pass` varchar(1000) NULL DEFAULT NULL COMMENT 'Contraseña cifrada con algoritmo seguro SHA1';
ALTER TABLE `usuarios` MODIFY COLUMN `id_Rol` int(11) NOT NULL COMMENT 'ID del rol asignado para control de permisos (FK rol)';
ALTER TABLE `usuarios` MODIFY COLUMN `idEmpresa` int(11) NOT NULL DEFAULT '1' COMMENT 'ID de la empresa a la que pertenece el usuario (FK empresas)';
ALTER TABLE `usuarios` MODIFY COLUMN `debe_cambiar_pass` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Bandera de seguridad para cambio obligatorio de contraseña: 1 = Obligatorio, 0 = Normal';
ALTER TABLE `usuarios` MODIFY COLUMN `activo` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Estado de la cuenta: 1 = Activa, 0 = Desactivada / Bloqueada';
ALTER TABLE `usuarios` MODIFY COLUMN `actualizado_en` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP on update current_timestamp() COMMENT 'Campo actualizado_en en tabla usuarios';
ALTER TABLE `usuario_plan_pago` COMMENT = 'Historial de suscripciones y membresías adquiridas por usuarios y comercios';
ALTER TABLE `usuario_plan_pago` MODIFY COLUMN `idUsuarioPlan` int(11) NOT NULL auto_increment COMMENT 'Identificador único del contrato de suscripción';
ALTER TABLE `usuario_plan_pago` MODIFY COLUMN `idUsuario` int(11) NOT NULL COMMENT 'ID del usuario o comercio suscriptor (FK usuarios)';
ALTER TABLE `usuario_plan_pago` MODIFY COLUMN `idPlanPago` int(11) NOT NULL COMMENT 'ID del plan de membresía contratado (FK plan_pago)';
ALTER TABLE `usuario_plan_pago` MODIFY COLUMN `fecha_inicio` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha y hora de inicio de la membresía';
ALTER TABLE `usuario_plan_pago` MODIFY COLUMN `fecha_fin` datetime NULL DEFAULT NULL COMMENT 'Fecha y hora de vencimiento del período contratado';
ALTER TABLE `usuario_plan_pago` MODIFY COLUMN `estado` enum('activo','vencido','cancelado') NOT NULL DEFAULT 'activo' COMMENT 'Estado de la suscripción: activo, vencido o cancelado';
ALTER TABLE `usuario_plan_pago` MODIFY COLUMN `monto_pagado` decimal(10,2) NULL DEFAULT '0.00' COMMENT 'Monto efectivamente cobrado por la membresía en USD';
ALTER TABLE `usuario_plan_pago` MODIFY COLUMN `observaciones` text NULL DEFAULT NULL COMMENT 'Notas adicionales o referencia de transacción de Wompi';
